using System.IO;
using System.Linq;
using System.Text;
using Ista.FileServices.Infrastructure.Interfaces;
using Ista.FileServices.MarketFiles.Models;
using Ista.FileServices.MarketFiles.Parsers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Rhino.Mocks;
using Should;

namespace Ista.FileServices.MarketFiles.UnitTests.MarketImports
{
    [TestClass]
    public class Xml810Scenarios
    {
        private ILogger logger;

        private Import810Xml concern;

        [TestInitialize]
        public void StartUp()
        {
            logger = MockRepository.GenerateStub<ILogger>();
            concern = new Import810Xml(logger);
        }

        [TestMethod]
        public void UI_Sample810_Invoice_DUAL()
        {
#region theXml
            
            const string xml = @"<ns0:Market810 xmlns:ns0=""http://CIS.Integration.Schema.Market.Common.Market810"">
	<TransactionCount>17</TransactionCount>
	<LdcDuns>006917967</LdcDuns>
	<LdcName>UNITED ILLUMINATING COMPANY</LdcName>
	<CspDuns>784087293</CspDuns>
	<CspName>LIBERTY POWER HOLDINGS, LLC</CspName>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2131002510002201302485</InvoiceNbr>
			<ReleaseNbr>2131002510002201302485_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2131002510002</EsiId>
			<CRAccountNumber>49951164684</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2111005195001201302304</InvoiceNbr>
			<ReleaseNbr>2111005195001201302304_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2111005195001</EsiId>
			<CRAccountNumber>4995702921</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2111007931001201302762</InvoiceNbr>
			<ReleaseNbr>2111007931001201302762_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2111007931001</EsiId>
			<CRAccountNumber>4995702922</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2130030273024201302265</InvoiceNbr>
			<ReleaseNbr>2130030273024201302265_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2130030273024</EsiId>
			<CRAccountNumber>4995753037</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2130034324020201302536</InvoiceNbr>
			<ReleaseNbr>2130034324020201302536_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2130034324020</EsiId>
			<CRAccountNumber>4995919878</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2131002205001201302583</InvoiceNbr>
			<ReleaseNbr>2131002205001201302583_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2131002205001</EsiId>
			<CRAccountNumber>4995919877</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>UNMET</ServiceClass>
					<ServicePeriodStartDate>20130117</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130215</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2220015178021201302096</InvoiceNbr>
			<ReleaseNbr>2220015178021201302096_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2220015178021</EsiId>
			<CRAccountNumber>49951217073</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130115</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130213</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000005270201302962</InvoiceNbr>
			<ReleaseNbr>3000000005270201302962_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000005270</EsiId>
			<CRAccountNumber>49951297885</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>2111003467002201302812</InvoiceNbr>
			<ReleaseNbr>2111003467002201302812_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>2111003467002</EsiId>
			<CRAccountNumber>49951298049</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000009876201302312</InvoiceNbr>
			<ReleaseNbr>3000000009876201302312_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000009876</EsiId>
			<CRAccountNumber>49951298050</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>UNMET</ServiceClass>
					<ServicePeriodStartDate>20130117</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130215</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000007097201302023</InvoiceNbr>
			<ReleaseNbr>3000000007097201302023_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000007097</EsiId>
			<CRAccountNumber>4995703180</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000008131201302466</InvoiceNbr>
			<ReleaseNbr>3000000008131201302466_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000008131</EsiId>
			<CRAccountNumber>4995703184</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130115</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130213</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000009830201302118</InvoiceNbr>
			<ReleaseNbr>3000000009830201302118_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000009830</EsiId>
			<CRAccountNumber>4995703190</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000015491201302463</InvoiceNbr>
			<ReleaseNbr>3000000015491201302463_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000015491</EsiId>
			<CRAccountNumber>4995703201</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000023518201302067</InvoiceNbr>
			<ReleaseNbr>3000000023518201302067_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000023518</EsiId>
			<CRAccountNumber>4995371728</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>3000000023517201302699</InvoiceNbr>
			<ReleaseNbr>3000000023517201302699_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3000000023517</EsiId>
			<CRAccountNumber>4995371727</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130116</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130214</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130216</TransactionDate>
			<InvoiceNbr>1920046315021201302363</InvoiceNbr>
			<ReleaseNbr>1920046315021201302363_867</ReleaseNbr>
			<TransactionTypeCode/>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>1920046315021</EsiId>
			<CRAccountNumber>49951307494</CRAccountNumber>
			<PaymentDueDate/>
			<TdspDuns>006917967</TdspDuns>
			<TdspName>UNITED ILLUMINATING COMPANY</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS, LLC</CrName>
			<TotalAmount>0</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>DUAL</BillPresenter>
			<BillCalculator/>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHCT006917967INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130114</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130212</ServicePeriodEndDate>
					<RateCode/>
					<DetailItemLoop>
						<DetailItem>
							<DetailItemChargeLoop/>
						</DetailItem>
					</DetailItemLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>0</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
</ns0:Market810>";
#endregion
            Import810Model context;

            using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(xml)))
            {
                var model = concern.Parse(stream);
                context = model as Import810Model;
            }

            context.ShouldNotBeNull();
            context.TransactionActualCount.ShouldEqual(17);
            context.TransactionAuditCount.ShouldEqual(17);

            var headers = context.TypeHeaders;
            headers.Length.ShouldEqual(17);
            
            var header = headers.First();
            header.TransactionSetId.ShouldEqual("810");
            header.TransactionSetControlNbr.ShouldBeEmpty();
            header.TransactionDate.ShouldEqual("20130216");
            header.InvoiceNbr.ShouldEqual("2131002510002201302485");
            header.ReleaseNbr.ShouldEqual("2131002510002201302485_867");
            header.TransactionTypeCode.ShouldBeEmpty();
            header.TransactionSetPurposeCode.ShouldEqual("00");
            header.OriginalInvoiceNbr.ShouldBeEmpty();
            header.EsiId.ShouldEqual("2131002510002");
            header.CrAccountNumber.ShouldEqual("49951164684");
            header.PaymentDueDate.ShouldBeEmpty();
            header.TdspDuns.ShouldEqual("006917967");
            header.TdspName.ShouldEqual("UNITED ILLUMINATING COMPANY");
            header.CrDuns.ShouldEqual("784087293");
            header.CrName.ShouldEqual("LIBERTY POWER HOLDINGS, LLC");
            header.TotalAmount.ShouldEqual("0");
            header.PreviousUtilityAccountNumber.ShouldBeEmpty();
            header.BillPresenter.ShouldEqual("DUAL");            
            header.BillCalculator.ShouldBeEmpty();

            header.Details.Length.ShouldEqual(1);
            var detail = header.Details.First();
            detail.AssignedId.ShouldEqual("1");
            detail.ServiceTypeCode.ShouldEqual("SV");
            detail.ServiceType.ShouldEqual("EL");
            detail.ServiceClassCode.ShouldEqual("C3");
            detail.ServiceClass.ShouldEqual("METER");
            detail.ServicePeriodStartDate.ShouldEqual("20130116");
            detail.ServicePeriodEndDate.ShouldEqual("20130214");
            
            detail.Items.Length.ShouldEqual(1);
            detail.Items.First().Charges.Length.ShouldEqual(0);
            detail.Items.First().Taxes.Length.ShouldEqual(0);

            header.Names.Length.ShouldEqual(1);
            var name = header.Names.First();
            name.EntityIdType.ShouldEqual("8R");

            header.Summaries.Length.ShouldEqual(1);
            var summary = header.Summaries.First();
            summary.TotalAmount.ShouldEqual("0");
            summary.TotalLineItems.ShouldEqual("1");
            
            header.Balances.Length.ShouldEqual(0);
            header.Messages.Length.ShouldEqual(0);
            header.Notes.Length.ShouldEqual(0);
            header.Payments.Length.ShouldEqual(0);
        }

        [TestMethod]
        public void Central_Hudson_Gas_Sample810_Invoice_RR()
        {
#region theXml
            
            const string xml = @"<ns0:Market810 xmlns:ns0=""http://CIS.Integration.Schema.Market.Common.Market810"">
	<TransactionCount>1</TransactionCount>
	<LdcDuns>006993695</LdcDuns>
	<LdcName>CENTRAL HUDSON GAS &amp; ELEC CORP</LdcName>
	<CspDuns>784087293</CspDuns>
	<CspName>LIBERTY POWER HOLDINGS LLC</CspName>
	<Transaction>
		<Header>
			<TransactionSetId>810</TransactionSetId>
			<TransactionDate>20130403</TransactionDate>
			<InvoiceNbr>B0000000000000324609</InvoiceNbr>
			<ReleaseNbr>U0000000000000575478</ReleaseNbr>
			<TransactionTypeCode>ME</TransactionTypeCode>
			<TransactionSetPurposeCode>00</TransactionSetPurposeCode>
			<OriginalInvoiceNbr/>
			<EsiId>3602081004</EsiId>
			<CRAccountNumber/>
			<PaymentDueDate/>
			<TdspDuns>006993695</TdspDuns>
			<TdspName>CENTRAL HUDSON GAS &amp; ELEC CORP</TdspName>
			<CrDuns>784087293</CrDuns>
			<CrName>LIBERTY POWER HOLDINGS LLC</CrName>
			<TotalAmount>39074</TotalAmount>
			<PreviousUtilityAccountNumber/>
			<BillPresenter>LDC</BillPresenter>
			<BillCalculator>LDC</BillCalculator>
			<CustomerDUNS/>
			<CommodityCode>EL</CommodityCode>
			<TradingPartnerID>LPHNY006993695INV</TradingPartnerID>
			<CustomerName>UNDEFINED</CustomerName>
			<CurrentBalance>UNDEFINED</CurrentBalance>
			<BusinessActivity>UNDEFINED</BusinessActivity>
			<StatementDate>UNDEFINED</StatementDate>
			<CustomerName2>UNDEFINED</CustomerName2>
			<CustomerName3>UNDEFINED</CustomerName3>
			<Address1>UNDEFINED</Address1>
			<Address2>UNDEFINED</Address2>
			<City>UNDEFINED</City>
			<State>UNDEFINED</State>
			<PostalCode>UNDEFINED</PostalCode>
			<ReceivedProcessedDate>UNDEFINED</ReceivedProcessedDate>
			<ESPAccountNumber>UNDEFINED</ESPAccountNumber>
			<PrePaidAmount>UNDEFINED</PrePaidAmount>
			<CurrencyCode>UNDEFINED</CurrencyCode>
			<TaxAmount1>UNDEFINED</TaxAmount1>
			<TaxAmount2>UNDEFINED</TaxAmount2>
			<PaymentLoop/>
			<DetailLoop>
				<Detail>
					<AssignedId>1</AssignedId>
					<ServiceTypeCode>SV</ServiceTypeCode>
					<ServiceType>EL</ServiceType>
					<ServiceClassCode>C3</ServiceClassCode>
					<ServiceClass>METER</ServiceClass>
					<ServicePeriodStartDate>20130305</ServicePeriodStartDate>
					<ServicePeriodEndDate>20130328</ServicePeriodEndDate>
					<RateCode/>
					<ServiceDeliveryPoint/>
					<DetailItemLoop>
						<DetailItem>
							<AssignedId>1</AssignedId>
							<DetailItemChargeLoop>
								<DetailItemCharge>
									<ChargeIndicator>C</ChargeIndicator>
									<AgencyCode>EU</AgencyCode>
									<ChargeCode>ENC001</ChargeCode>
									<Amount>36180</Amount>
									<Rate>0.0673</Rate>
									<UOM>KH</UOM>
									<Quantity>5376</Quantity>
								</DetailItemCharge>
							</DetailItemChargeLoop>
						</DetailItem>
					</DetailItemLoop>
					<DetailTaxLoop>
						<DetailTax>
							<MonetaryAmount>28.94</MonetaryAmount>
							<Percent>0.08</Percent>
							<RelationshipCode>A</RelationshipCode>
							<DollarBasis>361.8</DollarBasis>
							<JurisdictionCode/>
							<TaxTypeCode>LS</TaxTypeCode>
							<ExemptCode/>
							<Description/>
						</DetailTax>
					</DetailTaxLoop>
				</Detail>
			</DetailLoop>
			<NameLoop>
				<Name>
					<EntityIdType>8R</EntityIdType>
					<EntityName>MAHIMA CORPORATION</EntityName>
					<EntityName2/>
					<EntityName3/>
					<Address1/>
					<Address2/>
					<City/>
					<State/>
					<PostalCode/>
				</Name>
			</NameLoop>
			<SummaryLoop>
				<Summary>
					<TotalAmount>39074</TotalAmount>
					<TotalLineItems>1</TotalLineItems>
				</Summary>
				<SummaryTaxLoop>
					<SummaryTax/>
				</SummaryTaxLoop>
			</SummaryLoop>
			<NoteLoop/>
		</Header>
	</Transaction>
</ns0:Market810>";
#endregion
            Import810Model context;

            using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(xml)))
            {
                var model = concern.Parse(stream);
                context = model as Import810Model;
            }

            context.ShouldNotBeNull();
            context.TransactionActualCount.ShouldEqual(1);
            context.TransactionAuditCount.ShouldEqual(1);

            var headers = context.TypeHeaders;
            headers.Length.ShouldEqual(1);
            
            var header = headers.First();
            header.TransactionSetId.ShouldEqual("810");
            header.TransactionSetControlNbr.ShouldBeEmpty();
            header.TransactionDate.ShouldEqual("20130403");
            header.InvoiceNbr.ShouldEqual("B0000000000000324609");
            header.ReleaseNbr.ShouldEqual("U0000000000000575478");
            header.TransactionTypeCode.ShouldEqual("ME");
            header.TransactionSetPurposeCode.ShouldEqual("00");
            header.OriginalInvoiceNbr.ShouldBeEmpty();
            header.EsiId.ShouldEqual("3602081004");
            header.CrAccountNumber.ShouldBeEmpty();
            header.PaymentDueDate.ShouldBeEmpty();
            header.TdspDuns.ShouldEqual("006993695");
            header.TdspName.ShouldEqual("CENTRAL HUDSON GAS & ELEC CORP");
            header.CrDuns.ShouldEqual("784087293");
            header.CrName.ShouldEqual("LIBERTY POWER HOLDINGS LLC");
            header.TotalAmount.ShouldEqual("39074");
            header.PreviousUtilityAccountNumber.ShouldBeEmpty();
            header.BillPresenter.ShouldEqual("LDC");            
            header.BillCalculator.ShouldEqual("LDC");
            header.CustomerDUNS.ShouldBeEmpty();

            header.Details.Length.ShouldEqual(1);
            var detail = header.Details.First();
            detail.AssignedId.ShouldEqual("1");
            detail.ServiceTypeCode.ShouldEqual("SV");
            detail.ServiceType.ShouldEqual("EL");
            detail.ServiceClassCode.ShouldEqual("C3");
            detail.ServiceClass.ShouldEqual("METER");
            detail.ServicePeriodStartDate.ShouldEqual("20130305");
            detail.ServicePeriodEndDate.ShouldEqual("20130328");
            detail.RateCode.ShouldBeEmpty();
            detail.ServiceDeliveryPoint.ShouldBeEmpty();
            
            detail.Items.Length.ShouldEqual(1);
            var item = detail.Items.First();
            item.AssignedId.ShouldEqual("1");
            item.Charges.Length.ShouldEqual(1);

            var charge = item.Charges.First();
            charge.ChargeIndicator.ShouldEqual("C");
            charge.AgencyCode.ShouldEqual("EU");
            charge.ChargeCode.ShouldEqual("ENC001");
            charge.Amount.ShouldEqual("36180");
            charge.Rate.ShouldEqual("0.0673");
            charge.UOM.ShouldEqual("KH");
            charge.Quantity.ShouldEqual("5376");
            
            detail.Taxes.Length.ShouldEqual(1);
            var tax = detail.Taxes.First();
            tax.MonetaryAmount.ShouldEqual("28.94");
            tax.Percent.ShouldEqual("0.08");
            tax.RelationshipCode.ShouldEqual("A");
            tax.DollarBasis.ShouldEqual("361.8");
            tax.JurisdictionCode.ShouldBeEmpty();
            tax.TaxTypeCode.ShouldEqual("LS");
            tax.ExemptCode.ShouldBeEmpty();
            tax.Description.ShouldBeEmpty();

            header.Names.Length.ShouldEqual(1);
            var name = header.Names.First();
            name.EntityIdType.ShouldEqual("8R");
            name.EntityName.ShouldEqual("MAHIMA CORPORATION");
            name.EntityName2.ShouldBeEmpty();
            name.EntityName3.ShouldBeEmpty();
            name.Address1.ShouldBeEmpty();
            name.Address2.ShouldBeEmpty();
            name.City.ShouldBeEmpty();
            name.State.ShouldBeEmpty();
            name.PostalCode.ShouldBeEmpty();

            header.Summaries.Length.ShouldEqual(1);
            var summary = header.Summaries.First();
            summary.TotalAmount.ShouldEqual("39074");
            summary.TotalLineItems.ShouldEqual("1");

            header.Balances.Length.ShouldEqual(0);
            header.Messages.Length.ShouldEqual(0);
            header.Notes.Length.ShouldEqual(0);
            header.Payments.Length.ShouldEqual(0);
        }
    }
}
